# Generated by Django 5.2.3 on 2025-07-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_center',
            field=models.ImageField(blank=True, null=True, upload_to='products/center/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_left',
            field=models.ImageField(blank=True, null=True, upload_to='products/left/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_right',
            field=models.ImageField(blank=True, null=True, upload_to='products/right/'),
        ),
    ]
