# Generated by Django 5.2.3 on 2025-07-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_seller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
