# Generated by Django 5.2.3 on 2025-07-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expires_at',
        ),
    ]
